language: csharp
dotnet: 2.1
mono: none
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
branches:
  except:
  - /^w-.*$/
before_script:
  - (cd ./src && ./task restore)
script:
  - (cd ./src && ./task test)
