[package]
name = "example-lsp"
version = "0.1.0"
authors = ["vain0x <vainzerox@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
lsp-types = "0.56"
log = "0"
serde = "1"
serde_derive = "1"
serde_json = "1"
